### ISSUE TITLE
Starting xinit under a login shell?

### ISSUE THREAD

**Issue by CMB** [jsumners/autox#2]
When using autox, the session is not started from a login shell, so
profile files like /etc/profile, ~/.bash_profile, and so forth are
never sourced.  There are workarounds for that.
Mine was to make ~/.xinitrc a bash script, and forcibly source the
profile.  But I wonder if there's a better way.  Is there any way
we could get autox to run xinit under the user's login shell?
Is it a bad idea, or is it technically infeasible?

**Comment by jsumners** [comment]
I'm not opposed to a PR that implements what you are asking. I'm not very well versed on all of the details. But some quick searching leads me to believe that maybe using `pam_exec` instead of `system` to start `xinit` would work.

I wrote this to scratch a very specific itch (getting my HTPC running well). It's definitely not my area of expertise, so I am quite sure that a lot of improvement can be made.
